[project]
name = "fitness-tracker"
version = "0.1.0"
description = "A comprehensive Streamlit-based personal fitness and health tracking application"
requires-python = ">=3.11"
dependencies = [
    "extra-streamlit-components>=0.1.71",
    "plotly>=6.0.0",
    "streamlit>=1.42.2",
]